server:
  port: 8025

spring:
  application.name: file-server
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

filserserver:
  config:
    zip: false


