CREATE TABLE FILE_METADATA(
    DOCUMENT_ID VARCHAR(40) NOT NULL PRIMARY KEY,
    FILE_NAME VARCHAR(256) NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR(256) NOT NULL,
    PROCESS_ID VARCHAR(50) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP NOT NULL,
    BYTES INTEGER NOT NULL,
    FLAG_PERSISTED CHAR(1) NOT NULL DEFAULT 'N'
);

CREATE INDEX IND_FILE_METADATA_ORIGINAL_FILE_NAME ON FILE_METADATA(ORIGINAL_FILE_NAME);
CREATE INDEX IND_FILE_METADATA_PROCESS_ID ON FILE_METADATA(PROCESS_ID);
CREATE INDEX IND_FILE_METADATA_CREATE_DATE ON FILE_METADATA(CREATE_DATE);
CREATE INDEX IND_FILE_METADATA_UPDATE_DATE ON FILE_METADATA(UPDATE_DATE);
