CREATE TABLE FILE_METADATA(
    DOCUMENT_ID VARCHAR(40) NOT NULL PRIMARY KEY,
    FILE_NAME VARCHAR(256) NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR(256) NOT NULL,
    PROCESS_ID VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    BYTES INTEGER NOT NULL,
    FLAG_PERSISTED CHAR(1) NOT NULL DEFAULT 'N'
);

CREATE INDEX IND_FILE_METADATA_ORIGINAL_FILE_NAME ON FILE_METADATA(ORIGINAL_FILE_NAME);
CREATE INDEX IND_FILE_METADATA_PROCESS_ID ON FILE_METADATA(PROCESS_ID);
CREATE INDEX IND_FILE_METADATA_CREATED_DATE ON FILE_METADATA(CREATED_DATE);